### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by jlcd** [remorhaz/php-unilex#1]
Following up on https://github.com/remorhaz/php-json-path/issues/22

Will propose a fix.

**Comment by remorhaz** [comment]
I've reproduced memory leak. It's not in lookup table loader, as we thought initially, but somewhere in Parser::run(). I'll investigate it later today.

**Comment by remorhaz** [comment]
Update: the memory leak was due to use of mocked grammar; using real grammar doesn't produce any memory leak in my case. I wrote [this test](https://github.com/remorhaz/php-unilex/blob/master/tests/MemoryLeakTest.php) and it works. Maybe the problem is still outside UniLex library?

**Comment by remorhaz** [comment]
The problem was outside this library and has been resolved here: https://github.com/remorhaz/php-json-path/issues/23
